export enum LMFeedCustomActionEvents {
  OPEN_CREATE_POST_DIALOUGE = "OPEN_CREATE_POST_DIALOUGE",
  DELETE_POST = "DELETE_POST",
  REPORT_POST = "REPORT_POST",
  PIN_POST = "PIN_POST",
  UNPIN_POST = "UNPIN_POST",
  USER_INITIATED = "USER_INITIATED",
  REPLY_POSTED = "REPLY_POSTED",
}
